### ISSUE TITLE
Async error

### ISSUE THREAD

**Issue by PierrickGT** [suttna/botbuilder-redis-storage#1]
Hi,

I've tried to use your package but it looks like it's not working since I've got an error with async that should be supported since I'm using the last version of Node.
Here is the error:

```
2017-08-07T22:03:53.820632406Z app[web.1]: > node app.js
2017-08-07T22:03:53.820662843Z app[web.1]:
2017-08-07T22:04:01.413320260Z app[web.1]: /app/node_modules/botbuilder-redis-storage/lib/storage.js:22
2017-08-07T22:04:01.413532024Z app[web.1]:   async getData (context, callback) {
2017-08-07T22:04:01.413564260Z app[web.1]:         ^^^^^^^
2017-08-07T22:04:01.413620333Z app[web.1]:
2017-08-07T22:04:01.413648164Z app[web.1]: SyntaxError: Unexpected identifier
2017-08-07T22:04:01.413674618Z app[web.1]:     at createScript (vm.js:56:10)
2017-08-07T22:04:01.413728456Z app[web.1]:     at Object.runInThisContext (vm.js:97:10)
2017-08-07T22:04:01.413755375Z app[web.1]:     at Module._compile (module.js:542:28)
2017-08-07T22:04:01.413808351Z app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-08-07T22:04:01.413835873Z app[web.1]:     at Module.load (module.js:487:32)
2017-08-07T22:04:01.413889471Z app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-08-07T22:04:01.413917572Z app[web.1]:     at Function.Module._load (module.js:438:3)
2017-08-07T22:04:01.413944153Z app[web.1]:     at Module.require (module.js:497:17)
2017-08-07T22:04:01.413997789Z app[web.1]:     at require (internal/module.js:20:19)
2017-08-07T22:04:01.414024745Z app[web.1]:     at Object.<anonymous> (/app/node_modules/botbuilder-redis-storage/index.js:1:82)
```

Thank you for your help.

**Comment by bilby91** [comment]
Hi! @PierrickGT 

What version of node are you running ?

**Comment by PierrickGT** [comment]
The latest. 6.11.2

**Comment by bilby91** [comment]
@PierrickGT That explains your problem!

The latest version of node is 8.2.1. From what I know, async/await was introduced in node 7.6 so you will need to run a newer version of node to use the package.

Maybe we can transpile the code so that we support older version of node. Are you able to upgrade ?

**Comment by bilby91** [comment]
@PierrickGT Forget about my last comment, we can remove the `async` keyword since it's not actually being used. I will try to fix it today and release a new version to npm.

Thanks!

**Comment by bilby91** [comment]
@PierrickGT Try 1.0.2. Thanks!
